import sys
import json
import os

import keyboard
import openai


def ask_gpt(api_key, content, signature, clipboard_kw):
    if clipboard_kw in content:
        import pyperclip
        content = content.replace(clipboard_kw, pyperclip.paste())

    openai.api_key = api_key
    response = openai.ChatCompletion.create(
        model='gpt-3.5-turbo',
        messages=[
            {'role': 'user', 'content': content}
        ],
        temperature=0.7,
        stream=True
    )

    for chunk in response:
        if not chunk["choices"][0]["finish_reason"] == "stop":
            content = chunk["choices"][0]["delta"].get("content", None)
            if content:
                keyboard.write(content)
        else:
            if signature == '1':
                from datetime import datetime
                current = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                keyboard.write("\n[Generated by ChatGPT, {}]".format(current))


if __name__ == '__main__':
    params = sys.argv[1:]
    ask_gpt(*params)
